version: "3.8"

services:
  postgres-db:
    image: postgres:16.1
    container_name: anverali-tg-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend

  backend:
    container_name: anverali-tg-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
    networks:
      - backend

networks:
  backend:
    driver: bridge
